spring:
  jpa:
    hibernate:
      ddl-auto: create
  docker:
    compose:
      enabled: true
      file: ./docker/docker-compose.yml
      lifecycle-management: start-only
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cj
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  access-token-expiration: 10800
  secret: 5FwsE49eeFcoKguHGRSCOuo0WcOPVU++yav+yCDMfBM=